version: '3.3'

services:

  redis:
    image: redis
    network_mode: bridge
    restart: always
    container_name: redis

    
  db:
    image: postgres:9.4
    network_mode: bridge
    container_name: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  
  pythonFlask: 
    network_mode: bridge
    restart: always
    container_name: pythonFlask
    image: vasanth-vote-app
    build:
      context: vote/
      dockerfile: Dockerfile
      
      
  nodeJS: 
    network_mode: bridge
    restart: always
    container_name: nodeJS
    image: vasanth-node-app
    build:
      context: result/
      dockerfile: Dockerfile

  worker:
    network_mode: bridge
    restart: always
    container_name: worker
    image: vasanth-worker-app
    build:
      context: worker/
      dockerfile: Dockerfile

      
